application: nth-agent-798
version: 1
runtime: php
api_version: 1

handlers:
- url: /fetch\.pdf
  script: fetch.pdf
  
- url: /web/viewer\.js
  script: /web/viewer.js
  
- url: /(.+\.(gif|png|jpg|css|js|properties))$
  static_files: \1
  upload: .+\.(gif|png|jpg|css|js|properties)$
  application_readable: true
  
- url: /(.+\.(php|html))$
  script: \1